SG2002_IPC_COMPONENT := $(COMPONENTS_ROOT)/sg2002-ipc
SG2002_IPC_BUILD_ROOT := $(BUILDDIR)/components/sg2002-ipc
SG2002_IPC_SDK_DIR := $(SG2002_IPC_BUILD_ROOT)/sdk
SG2002_IPC_FIRMWARE_ELF := $(SG2002_IPC_SDK_DIR)/freertos/cvitek/install/bin/cvirtos.elf
SG2002_IPC_FIRMWARE_BIN := $(SG2002_IPC_SDK_DIR)/freertos/cvitek/install/bin/cvirtos.bin

$(BUILDDIR)/sg2002-ipc-build-stamp:
	@echo "$(COLOUR_GREEN)Building SG2002 IPC component for $(BOARD)$(END_COLOUR)"
	@$(MAKE) -C $(SG2002_IPC_COMPONENT) firmware \
		BOARD=$(BOARD) CONFIG_ROOT=$(CONFIG_ROOT) \
		SDK_CACHE=$(SDK_CACHE) BUILD_ROOT=$(SG2002_IPC_BUILD_ROOT) \
		OUTPUT_DIR=$(OUTPUT_DIR) HOST_TOOLS=$(HOST_TOOLS) \
		RTOS_CROSS_COMPILE=$(RTOS_CROSS_COMPILE)
	@test -s $(SG2002_IPC_FIRMWARE_ELF)
	@test -s $(SG2002_IPC_FIRMWARE_BIN)
	@touch $@

$(BUILDDIR)/sg2002-ipc-stamp: $(BUILDDIR)/sg2002-ipc-build-stamp
	@echo "$(COLOUR_GREEN)Installing SG2002 IPC component for $(BOARD)$(END_COLOUR)"
	@$(MAKE) -C $(SG2002_IPC_COMPONENT) install \
		BOARD=$(BOARD) CONFIG_ROOT=$(CONFIG_ROOT) \
		SDK_CACHE=$(SDK_CACHE) BUILD_ROOT=$(SG2002_IPC_BUILD_ROOT) \
		OUTPUT_DIR=$(OUTPUT_DIR) DESTDIR=$(ROOTFS) \
		VENDOR_INCLUDE=$(SG2002_IPC_SDK_DIR)/cvi_mpi/include \
		HOST_TOOLS=$(HOST_TOOLS) \
		CROSS_COMPILE=$(CROSS_COMPILE) RTOS_CROSS_COMPILE=$(RTOS_CROSS_COMPILE)
	@touch $@
